spring:
  application:
    name: ms-one
  config:
    import: configserver:http://localhost:8888
  datasource:
      username: sa
      password: 
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"